
version: "3.9"
services:

  owa:
    image: openwa/wa-automate:latest
    hostname: owa
    init: true
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - "sessions:/sessions"
    ports:
      - "8080:8080"
    # configure use of EasyAPI CLI Flags documented here: https://docs.openwa.dev/docs/configuration/command-line-options
    # You can use environment variables instead of command line flags to set your desired configuration
    # every CLI flag cas a corresponding environment variable: Simly add WA_ to the flag and change it UPPER_CASE_WITH_UNDERSCORES
    # eg: -qr-max 3 becomes WA_QR_MAX=3
    #     --disable-spins becomes WA_DISABLE_SPINS=true
    # Note that this will not work on the alias flag, you have to use the whole flag, e.g  -w cannot become WA_W, it has to be WA_WEBHOOK
    environment:
      WA_PORT: 8080
      #WA_MULTI-DEVICE: true
      #WA_DISABLE_SPINS: true
      #WA_LICENSE_KEY: '00000000-000000000-00000000-00000000'    # Need a licence? -> https://smashah.gumroad.com/l/open-wa?tier=1%20Restricted%20License%20Key
      #WA_SESSION_ID: 'auniquesessionid'
      #WA_WEBHOOK: 'https://yourwebhook.com' 
      #WA_QR_MAX: 15

    # OR you can Enter command line flags directly  by uncommenting the command: entry below
    #command: -p 8080 --multi-device --disable-spins -l '00000000-000000000-00000000-00000000' --session-id "auniquesessionid" -w 'https://yourwebhook.com' --qr-max 3 

volumes:
  sessions:
